Implement reviews row actions for the Product reviews page table
godaddy-wordpress/woocommerce pull request #25
Opened 2022-04-14 09:52 UTC by unfulvio-godaddy

# Summary

Implements the row actions for the product reviews page.

### Story: [MWC 5343](https://jira.godaddy.com/browse/MWC-5352)

## QA

- [ ] Code review
- [ ] Unit tests pass

## Details 

This is an almost exact copy of `WP_Comments_List_Table::handle_row_actions()` minus wording. 

The JS functionality will be addressed in [MWC-5353](https://jira.godaddy.com/browse/MWC-5353).

Also, we probably need a follow up story to ensure the menu item keeps focus when editing a review from the product reviews page. 

## QA

- [ ] Code review
- [ ] Unit tests pass

### User testing

1. Have multiple reviews and replies in your installation
1. Go to the Products > Reviews page
    - [ ] Hovering on individual rows will display the actions 
    - [ ] Clicking on the edit button will allow you to edit a review

The JS for quick edit and inline reply are expected not to work yet.

2022-04-14 15:36 UTC, agibson-godaddy requested changes

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +					$unapprove_url,
I understand this was copied from WordPress core, but I'd be in favour of reworking this to escape late. So remove the `esc_url()`s from lines 246-252, and put them here instead.

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +					"delete:the-comment-list:comment-{$review->comment_ID}:e7e7d3:action=dim-comment&amp;new=unapproved",
I think we should run these lines through `esc_attr()` because we have the comment ID variable in there.

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +					"delete:the-comment-list:comment-{$review->comment_ID}:e7e7d3:action=dim-comment&amp;new=unapproved",
I think we should run these lines through `esc_attr()` because we have the comment ID variable in there.

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +					__( 'Unapprove', 'woocommerce' )
```suggestion
					esc_html__( 'Unapprove', 'woocommerce' )
```

(I suggest this change for all the lines in question.)

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +					__( 'Unapprove', 'woocommerce' )
```suggestion
					esc_html__( 'Unapprove', 'woocommerce' )
```

(I suggest this change for all the lines in question.)

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +		$url = "comment.php?c=$review->comment_ID";
In general I'd be in favour of replacing this with `add_query_arg()`, but at minimum I'd `urlencode()` that review ID.

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +		$url = "comment.php?c=$review->comment_ID";
In general I'd be in favour of replacing this with `add_query_arg()`, but at minimum I'd `urlencode()` that review ID.

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +				"comment.php?action=editcomment&amp;c={$review->comment_ID}",
This needs an `esc_url()`, but I'd also be in favour of:

1. Use `add_query_arg()`
2. Use `admin_url( 'comment.php' )`
3. `urlencode()` the review ID.

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +				"comment.php?action=editcomment&amp;c={$review->comment_ID}",
This needs an `esc_url()`, but I'd also be in favour of:

1. Use `add_query_arg()`
2. Use `admin_url( 'comment.php' )`
3. `urlencode()` the review ID.

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +				$review->comment_post_ID,
```suggestion
				esc_attr( $review->comment_ID ),
				esc_attr( $review->comment_post_ID ),
```

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +				$review->comment_post_ID,
```suggestion
				esc_attr( $review->comment_ID ),
				esc_attr( $review->comment_post_ID ),
```

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +				$review->comment_post_ID,
```suggestion
				esc_attr( $review->comment_ID ),
				esc_attr( $review->comment_post_ID ),
```

2022-04-14 15:36 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +				$review->comment_post_ID,
```suggestion
				esc_attr( $review->comment_ID ),
				esc_attr( $review->comment_post_ID ),
```

2022-04-19 12:30 UTC, agibson-godaddy reviewed
I pushed up one change: https://github.com/godaddy-wordpress/woocommerce/pull/25/commits/f5460325d4dcf7fcb8445cfd9d002a5dae7ef4f7

1. I think we should use `wp_nonce_url()` instead of adding in the nonce manually.
2. We should use `add_query_arg()` instead of manually appending args.

Overall this LGTM and QA passes but I left a question about if a filter should be removed.

2022-04-19 12:30 UTC, agibson-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +		$actions = apply_filters( 'comment_row_actions', array_filter( $actions ), $item );
I wonder if we should remove this. I also included a core filter in one of my PRs and @dmagalhaes-godaddy suggested removing it.

2022-04-20 00:29 UTC, unfulvio-godaddy commented
@agibson-godaddy I have removed 2 WP core filters used in this class

2022-04-20 00:30 UTC, unfulvio-godaddy commented on plugins/woocommerce/src/Internal/Admin/ReviewsListTable.php
> +		$actions = apply_filters( 'comment_row_actions', array_filter( $actions ), $item );
I removed it along with another in the author column

2022-04-20 10:17 UTC, agibson-godaddy approved these changes

2022-04-20 10:17 UTC, merged